apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-task5
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops-task5
  template:
    metadata:
      labels:
        app: mlops-task5
    spec:
      containers:
        - name: mlops-task5
          image: mlops-task5:latest
          ports:
            - containerPort: 5000
