# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-task5-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-task5
  template:
    metadata:
      labels:
        app: mlops-task5
    spec:
      containers:
        - name: mlops-task5-container
          image: rayyanatttaullah09/mlops_task_02:latest
          ports:
            - containerPort: 5000
