# kubernetes/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Mlops-task5-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Mlops-task5
  template:
    metadata:
      labels:
        app: Mlops-task5
    spec:
      containers:
        - name: Mlops-task5-container
          image: rayyanatttaullah09/mlops_task_02:latest
          ports:
            - containerPort: 5000
